popupActions:
  - fileNameRegExp: ".*"
    openUrlAction:
      description: "Master"
      icon: "/icons/gitlab-16x15.svg"
      urlWithParameters: "https://gitlab.link/java/business/{appName}/-/tree/master/{fileNameWithPath}"
  - fileNameRegExp: "^(?!.*Test\\.(java|kt)$).*\\.(java|kt)$"
    multiplyOpenUrlAction:
      description: "Coverage"
      icon: "/icons/sonarqube-16x15.svg"
      openUrlActions:
        - description: "Reviews сoverage"
          icon: "/icons/sonarqube-16x15.svg"
          urlWithParameters: "https://sonar.rev/code?id={appName}-master&selected={appName}-master:{fileNameWithPath}"
        - description: "Master сoverage"
          icon: "/icons/sonarqube-16x15.svg"
          urlWithParameters: "https://sonar.dev/code?id={appName}-master&selected={appName}-master:{fileNameWithPath}"

yamlActions:
  - keyPathRegExp: "sharedEnvSecretVars\\.\\[[0-9]+\\]\\.secretKeyRefName"
    valueRegExp: "some-value"
    marginAction:
      openUrlAction:
        description: "Config"
        icon: "/icons/k8s-16x16.svg"
        urlWithParameters: "https://k8s.link/#/configmap/develop/config-{yamlValue}?namespace=develop"

mavenActions:
  - keyPathRegExp: "project.dependencies.dependency\\.\\[[0-9]+\\]\\.artifactId"
    valueRegExp: "company-spring-boot-starter"
    marginAction:
      openUrlAction:
        description: "Source"
        icon: "/icons/gitlab-16x15.svg"
        urlWithParameters: "https://gitlab.link/java/business/company-spring-boot-starter/-/tree/master/"

methodCalledCodeActions:
  - callerClass: "org.slf4j.Logger"
    marginAction:
      multiplyOpenUrlAction:
        description: "Открыть логи"
        icon: "/icons/kibana-16x16.svg"
        openUrlActions:
          - description: "Открыть логи в тесте"
            icon: "/icons/kibana-16x16.svg"
            urlWithParameters: "https://kibana-test.com/app/discover#/?_a=(columns:!(_source),filters:!((query:(match_phrase:(application.keyword:{appName}))),(query:(match_phrase:(app_environment:test)))),query:(language:lucene,query:'{queryString}'),sort:!())"
          - description: "Открыть логи в проде"
            icon: "/icons/kibana-16x16.svg"
            urlWithParameters: "https://kibana-prod.com/app/discover#/?_a=(columns:!(_source),filters:!((query:(match_phrase:(application.keyword:{appName}))),(query:(match_phrase:(app_environment:test)))),query:(language:lucene,query:'{queryString}'),sort:!())"

annotationCodeActions:
  - callerClass: "ru.yourcompany.Tracing"
    marginAction:
      openUrlAction:
        description: "Открыть Jaeger"
        icon: "/icons/jaeger-16x16.svg"
        urlWithParameters: "https://jaeger.link/"

interfaceImplementationActions:
  - callerClass: "graphql.kickstart.tools.GraphQLResolver"
    marginAction:
      openUrlAction:
        description: "Открыть GraphQL Schema"
        icon: "/icons/graphql-16x16.svg"
        urlWithParameters: "https://graphql.link/"